[package]
name = "brainheck"
version = "0.1.0"
authors = ["Garen Tyler <garentyler@garen.dev>"]
edition = "2018"

[dependencies]
clap = "*"

[dev-dependencies]
criterion = "*"

[[bench]]
name = "interpreter"
harness = false